### import the module you need first

In [2]:
import numpy as np

## step1. 
#### Construct a numpy array represent the equations.
#### the coefficients,answers and augmented matrix of each equation need to be stored separately.

In [2]:
"""
example:
 
5y-7z = 7        | 0 5 -7 7 |
4x-z = 8      -> | 4 0 -1 8 |
x-y+z = 9        | 1 -1 1 9 |
"""

'\nexample:\n \n5y-7z = 7        | 0 5 -7 7 |\n4x-z = 8      -> | 4 0 -1 8 |\nx-y+z = 9        | 1 -1 1 9 |\n'

In [3]:
# 這邊我直接用np的功能建立矩陣，注意這邊我直接先加好小數點不然後面計算會有問題
arr1 = np.array([[0.0, 5.0, -7.0, 7.0],[4.0, 0.0, -1.0, 8.0], [1.0, -1.0, -1.0, 9.0]])
print(arr1)

[[ 0.  5. -7.  7.]
 [ 4.  0. -1.  8.]
 [ 1. -1. -1.  9.]]


## step2. 
### Before doing gauss elimination,
### we need to check if the first element([0,0]) of the augmented matrix is zero or not.
### If the first element is zero,
### we need to find another row whose first element isn't zero,and change them.

In [3]:
#如果矩陣最左上角的數字不為0，就先找一個第一個不為0的列交換位置，因為要整列交換位置所以用for-loop來操作
if arr1[0][0]==0:
    for i in range(4):
        temp = arr1[0][i]
        arr1[0][i] = arr1[1][i]
        arr1[1][i] = np.round(temp, 2)
print(arr1)

[[ 4.  0. -1.  8.]
 [ 0.  5. -7.  7.]
 [ 1. -1. -1.  9.]]


In [5]:
#test:step2
#print the new augment matrix

## step3. gauss elimination

#### print the matrix after  gauss elimination

In [6]:
# 為了操作高斯消去法，使用for-loop來操作RowScalar&RowAddition
for i in range(4):
    arr1[2][i] = arr1[2][i]+arr1[0][i]*(-0.25)


for i in range(4):
    arr1[2][i] = arr1[2][i]+arr1[1][i]*(0.2)
print("the augment matrix after gauss eliminatio:")
print(arr1)
        

the augment matrix after gauss eliminatio:
[[ 4.    0.   -1.    8.  ]
 [ 0.    5.   -7.    7.  ]
 [ 0.    0.   -2.15  8.4 ]]


In [7]:
#test:step3
#print the augment matrix after gauss elimination

## step4. LU decomposition(bonus)

## if you don't want to submit bouns,you don't need to do  step4 and step5

In [5]:
# initiate U矩陣
arr2 = np.array([[0.0, 5.0, -7.0],[4.0, 0.0, -1.0], [1.0, -1.0, -1.0]])
print(arr2)
# initiate L矩陣
arr3 = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])
if arr2[0][0]==0:
    for i in range(3):
        temp = arr2[0][i]
        arr2[0][i] = arr2[1][i]
        arr2[1][i] = np.round(temp, 2)
# print(arr2)
# 計算RowScalar&RowAddition要乘上去的數值，其同時也是L矩陣的值
a1 = (-1)*arr2[2][0]/arr2[0][0]
arr3[2][0] = (-1)*a1
# print(a1)
for i in range(3):
    arr2[2][i] = arr2[2][i]+arr2[0][i]*a1

a2 = (-1)*arr2[2][1]/arr2[1][1]
print(a2)
arr3[2][1] = (-1)*a2

for i in range(3):
    arr2[2][i] = arr2[2][i]+arr2[1][i]*(a2)
    
print("L:")
print(arr3)
    
print("U:")
print(arr2)
        

[[ 0.  5. -7.]
 [ 4.  0. -1.]
 [ 1. -1. -1.]]
0.2
L:
[[ 1.    0.    0.  ]
 [ 0.    1.    0.  ]
 [ 0.25 -0.2   1.  ]]
U:
[[ 4.    0.   -1.  ]
 [ 0.    5.   -7.  ]
 [ 0.    0.   -2.15]]


In [9]:
#print L and U

## step5. check the ansewer of LU(bonus)

please use the function in scipy.linalg to check your answer

the documentatin of scipy.linalg :
https://docs.scipy.org/doc/scipy/reference/linalg.html

In [6]:
import scipy.linalg as la
A = np.array([[0, 5, -7], [4, 0, -1], [1, -1, -1]])
# 使用lu fuction可以Compute pivoted LU decomposition of a matrix.
P, L, U = la.lu(A)
print("L:")
print(L)
print("U:")
print(U)

L:
[[ 1.    0.    0.  ]
 [ 0.    1.    0.  ]
 [ 0.25 -0.2   1.  ]]
U:
[[ 4.    0.   -1.  ]
 [ 0.    5.   -7.  ]
 [ 0.    0.   -2.15]]
